version: '3'
services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - bridge
  php:
    build: ./php

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
      - ./sock:/sock
    depends_on:
      - db
    networks:
      - bridge
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/symfony:cached
      - ./sock:/sock
    networks:
      - bridge

networks:
  bridge:
