<?php

namespace AppBundle\Repository;

/**
 * SensorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorsRepository extends \Doctrine\ORM\EntityRepository
{
}
